frr defaults traditional
hostname r6
!
interface lo
 ip address 6.6.6.6/32
!
interface eth1
 ip address 10.1.46.2/30
!
router bgp 65003
 bgp router-id 6.6.6.6
 no bgp ebgp-requires-policy
 neighbor 10.1.46.1 remote-as 65001
 address-family ipv4 unicast
  network 6.6.6.6/32
 exit-address-family
!
