frr version 10.1_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
 ip ospf cost 100
exit
!
interface eth2
 ip address 10.0.13.1/30
 ip ospf area 0
exit
!
interface eth3
 ip address 10.1.15.1/30
exit
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 4.4.4.4 remote-as 65001
 neighbor 4.4.4.4 update-source lo
 neighbor 10.1.15.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 1.1.1.1/32
  neighbor 4.4.4.4 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.1
 redistribute bgp
exit
!
