frr version 10.1_git
frr defaults traditional
hostname r3
no ipv6 forwarding
!
interface eth1
 ip address 10.0.13.2/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.0.34.1/30
 ip ospf area 0
exit
!
interface lo
 ip address 3.3.3.3/32
 ip ospf area 0
exit
!
router ospf
 ospf router-id 3.3.3.3
exit
!
