frr version 10.1_git
frr defaults traditional
hostname r4
no ipv6 forwarding
!
interface eth1
 ip address 10.0.24.2/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.0.34.2/30
 ip ospf area 0
exit
!
interface eth3
 ip address 10.1.46.1/30
exit
!
interface lo
 ip address 4.4.4.4/32
 ip ospf area 0
exit
!
router bgp 65001
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 1.1.1.1 remote-as 65001
 neighbor 1.1.1.1 update-source lo
 neighbor 10.1.46.2 remote-as 65003
 !
 address-family ipv4 unicast
  network 4.4.4.4/32
  neighbor 1.1.1.1 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 4.4.4.4
 redistribute bgp
exit
!
